### ISSUE TITLE
Error Langchain import lunary

### ISSUE THREAD

**Issue by Nerickounet** [lunary-ai/lunary-js#14]
I have this error while importing lunary with langchain

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './langchain' is not defined by "exports" in C:\Users\e.roquefort\git\ia-qualitel\node_modules\lunary\package.json imported from C:\Users\e.roquefort\git\ia-qualitel\node_modules\@langchain\community\dist\callbacks\handlers\lunary.js

The solution is to add this to package.json in lunary project : 

"exports": {
....
    "./langchain": {
      "types": "./dist/langchain.d.ts",
      "import": "./dist/langchain.js",
      "require": "./dist/langchain.cjs"
    }
}

**Comment by vincelwt** [comment]
Hi @Nerickounet Thank you for reporting! We mistakenly published a version with the old package.json. 
Should be fixed with the latest :)
