### ISSUE TITLE
Using "trackEvent" instead of wrapping own function intended? 

### ISSUE THREAD

**Issue by nkuehn** [lunary-ai/lunary-js#8]
Hi, the docs for custom implementations are focused on the JS wrapping method but the code also has a function to directly trigger tracking an event from withing the application logic:

https://github.com/llmonitor/llmonitor-js/blob/main/src/llmonitor.ts#L49

That would be much more suitable for evaluation because the wrapping method forces to refactor the own codebase into matching the expected data structures for the conversation and messages.   That's not really useful just to evaluate, also our own data structure has much more metadata information and other pass-through that is not adhering to the type.  

Is directly calling `trackEvent()` asynchronously an intended usage scenario?

**Comment by vincelwt** [comment]
Hi @nkuehn, thanks for the feedback!

I actually agree. The wrapping isn't convenient for all use-cases. 
We're planning on documenting this method as we overhaul the docs in the next days, so you can go ahead and use that.

Are you building a chat app? I'd recommend to do the tracking of chat messages and conversations on the frontend, so you can later tie that to feedback tracking and more. 

Happy to help with the integration if you have any issue!

**Comment by nkuehn** [comment]
We're going a different path with the tooling now, but nevertheless feedback on the frontend aspect:  Tracking from the frontend is just superficially convenient but has a lot of limits.  
 - would have to expose all internal metrics to the frontend to do proper in-depth observation.  Tokens used internally, model paremters, exact timings of which step is happening internally - alone the fact that the internal processing chain would be exposed at all.   non of that is of any business to the general public. 
 - would expose user IP addresses to you, which would make the whole data protection approval unnecessarily hard

**Comment by vincelwt** [comment]
Saw this issue is still open, we do have a trackEvent method now documented: https://lunary.ai/docs/js/custom
Thanks for the feedback @nkuehn !
